import os
from pathlib import Path

try:
    from dotenv import load_dotenv
except ImportError:
    def load_dotenv(*args, **kwargs):  # type: ignore[no-redef]
        return False

# Get project root directory (parent of backend/)
ROOT_DIR_PATH = Path(__file__).resolve().parent.parent
ROOT_DIR = str(ROOT_DIR_PATH)

# Load .env automatically. Environment variables still win over file values.
load_dotenv(ROOT_DIR_PATH / ".env", override=False)
load_dotenv(ROOT_DIR_PATH / "whisper_config.env", override=False)


def _env(name: str, default: str) -> str:
    value = os.getenv(name)
    if value is None or value == "":
        return default
    return value


def _env_int(name: str, default: int) -> int:
    try:
        return int(_env(name, str(default)))
    except ValueError:
        return default


def _env_float(name: str, default: float) -> float:
    try:
        return float(_env(name, str(default)))
    except ValueError:
        return default


def _env_bool(name: str, default: bool = False) -> bool:
    value = _env(name, "true" if default else "false").strip().lower()
    return value in {"1", "true", "yes", "on"}


# --- Milvus settings ---
MILVUS_HOST = _env("MILVUS_HOST", "localhost")
MILVUS_PORT = _env("MILVUS_PORT", "19530")
KEYFRAME_COLLECTION_NAME = _env("KEYFRAME_COLLECTION_NAME", "video_keyframes")

# Keep this in sync with the active visual model. SigLIP2 SO400M projection is 1152d.
VECTOR_DIMENSION = _env_int("VECTOR_DIMENSION", 1152)

# Compatibility aliases / service URLs (used by scripts expecting these names)
ELASTICSEARCH_URL = _env("ELASTICSEARCH_URL", "http://localhost:9200")

# MinIO (object storage)
MINIO_ENDPOINT = _env("MINIO_ENDPOINT", "http://localhost:9000")
MINIO_ACCESS_KEY = _env("MINIO_ACCESS_KEY", "minioadmin")
MINIO_SECRET_KEY = _env("MINIO_SECRET_KEY", "minioadmin")
MINIO_BUCKET = _env("MINIO_BUCKET", "milvus")

# --- Data paths (absolute from project root) ---
DATA_DIR = Path(_env("DATA_DIR", str(ROOT_DIR_PATH / "data"))).resolve()
VIDEOS_DIR = _env("VIDEOS_DIR", str(DATA_DIR / "videos"))
KEYFRAMES_DIR = _env("KEYFRAMES_DIR", str(DATA_DIR / "keyframes"))
TRANSCRIPTS_DIR = _env("TRANSCRIPTS_DIR", str(DATA_DIR / "transcripts"))
OCR_RESULTS_DIR = _env("OCR_RESULTS_DIR", str(DATA_DIR / "ocr_result"))
CAPTIONS_DIR = _env("CAPTIONS_DIR", str(DATA_DIR / "captions"))
CLIP_FEATURES_DIR = _env("EMBEDDINGS_DIR", str(DATA_DIR / "embeddings"))
EMBEDDINGS_DIR = CLIP_FEATURES_DIR

# --- Model registry ---
# Competition default: Vietnamese UI query -> English visual query with SigLIP2 NaFlex.
# If you switch models, recompute embeddings and recreate the Milvus collection.
VISUAL_MODEL_PROVIDER = _env("VISUAL_MODEL_PROVIDER", "siglip2").lower()
VISUAL_MODEL_NAME = _env("VISUAL_MODEL", _env("CLIP_MODEL_NAME", "google/siglip2-so400m-patch16-naflex"))
VISUAL_MODEL_PRETRAINED = _env("VISUAL_MODEL_PRETRAINED", _env("CLIP_PRETRAINED", ""))
MODEL_TRUST_REMOTE_CODE = _env_bool("MODEL_TRUST_REMOTE_CODE", True)
VISUAL_TRUNCATE_DIM = _env_int("VISUAL_TRUNCATE_DIM", VECTOR_DIMENSION)

# Backwards-compatible names used by existing scripts.
CLIP_MODEL_NAME = VISUAL_MODEL_NAME
CLIP_PRETRAINED = VISUAL_MODEL_PRETRAINED

TEXT_MODEL_PROVIDER = _env("TEXT_MODEL_PROVIDER", "none").lower()
TEXT_MODEL_NAME = _env("TEXT_MODEL", "BAAI/bge-m3")
RERANK_MODEL_PROVIDER = _env("RERANK_MODEL_PROVIDER", "sentence_transformers").lower()
RERANK_MODEL_NAME = _env("RERANK_MODEL", "BAAI/bge-reranker-v2-m3")
ASR_MODEL = _env("ASR_MODEL", _env("WHISPER_MODEL", "large-v3"))
ASR_LANGUAGE = _env("ASR_LANGUAGE", "vi")
OCR_ENGINE = _env("OCR_ENGINE", "paddleocr").lower()
OCR_LANGUAGES = [lang.strip() for lang in _env("OCR_LANGUAGES", "en,vi").split(",") if lang.strip()]

# --- Retrieval defaults ---
VISUAL_MAX_RESULTS = _env_int("VISUAL_MAX_RESULTS", 500)
TEXT_MAX_RESULTS = _env_int("TEXT_MAX_RESULTS", 500)
FINAL_MAX_RESULTS = _env_int("FINAL_MAX_RESULTS", 500)
RERANK_TOP_K = _env_int("RERANK_TOP_K", 50)
RRF_K = _env_int("RRF_K", 60)
WEIGHT_VISUAL = _env_float("WEIGHT_VISUAL", 1.0)
WEIGHT_TRANSCRIPT = _env_float("WEIGHT_TRANSCRIPT", 1.0)
WEIGHT_OCR = _env_float("WEIGHT_OCR", 1.0)
WEIGHT_CAPTION = _env_float("WEIGHT_CAPTION", 0.8)
ENABLE_QUERY_TRANSLATION = _env_bool("ENABLE_QUERY_TRANSLATION", True)
QUERY_TRANSLATION_PROVIDER = _env("QUERY_TRANSLATION_PROVIDER", "nllb").lower()
QUERY_TRANSLATION_MODEL = _env("QUERY_TRANSLATION_MODEL", "facebook/nllb-200-distilled-600M")
QUERY_TRANSLATION_SRC_LANG = _env("QUERY_TRANSLATION_SRC_LANG", "vie_Latn")
QUERY_TRANSLATION_TGT_LANG = _env("QUERY_TRANSLATION_TGT_LANG", "eng_Latn")
QUERY_TRANSLATION_MAX_LENGTH = _env_int("QUERY_TRANSLATION_MAX_LENGTH", 128)

OBJECT_LABELS = [
    "Tortoise",
    "Container",
    "Magpie",
    "Sea turtle",
    "Football",
    "Ambulance",
    "Ladder",
    "Toothbrush",
    "Syringe",
    "Sink",
    "Toy",
    "Organ",
    "Cassette deck",
    "Apple",
    "Human eye",
    "Cosmetics",
    "Paddle",
    "Snowman",
    "Beer",
    "Chopsticks",
    "Human beard",
    "Bird",
    "Parking meter",
    "Traffic light",
    "Croissant",
    "Cucumber",
    "Radish",
    "Towel",
    "Doll",
    "Skull",
    "Washing machine",
    "Glove",
    "Tick",
    "Belt",
    "Sunglasses",
    "Banjo",
    "Cart",
    "Ball",
    "Backpack",
    "Bicycle",
    "Home appliance",
    "Centipede",
    "Boat",
    "Surfboard",
    "Boot",
    "Headphones",
    "Hot dog",
    "Shorts",
    "Fast food",
    "Bus",
    "Boy",
    "Screwdriver",
    "Bicycle wheel",
    "Barge",
    "Laptop",
    "Miniskirt",
    "Drill",
    "Dress",
    "Bear",
    "Waffle",
    "Pancake",
    "Brown bear",
    "Woodpecker",
    "Blue jay",
    "Pretzel",
    "Bagel",
    "Tower",
    "Teapot",
    "Person",
    "Bow and arrow",
    "Swimwear",
    "Beehive",
    "Brassiere",
    "Bee",
    "Bat",
    "Starfish",
    "Popcorn",
    "Burrito",
    "Chainsaw",
    "Balloon",
    "Wrench",
    "Tent",
    "Vehicle registration plate",
    "Lantern",
    "Toaster",
    "Flashlight",
    "Billboard",
    "Tiara",
    "Limousine",
    "Necklace",
    "Carnivore",
    "Scissors",
    "Stairs",
    "Computer keyboard",
    "Printer",
    "Traffic sign",
    "Chair",
    "Shirt",
    "Poster",
    "Cheese",
    "Sock",
    "Fire hydrant",
    "Land vehicle",
    "Earrings",
    "Tie",
    "Watercraft",
    "Cabinetry",
    "Suitcase",
    "Muffin",
    "Bidet",
    "Snack",
    "Snowmobile",
    "Clock",
    "Medical equipment",
    "Cattle",
    "Cello",
    "Jet ski",
    "Camel",
    "Coat",
    "Suit",
    "Desk",
    "Cat",
    "Bronze sculpture",
    "Juice",
    "Gondola",
    "Beetle",
    "Cannon",
    "Computer mouse",
    "Cookie",
    "Office building",
    "Fountain",
    "Coin",
    "Calculator",
    "Cocktail",
    "Computer monitor",
    "Box",
    "Stapler",
    "Christmas tree",
    "Cowboy hat",
    "Hiking equipment",
    "Studio couch",
    "Drum",
    "Dessert",
    "Wine rack",
    "Drink",
    "Zucchini",
    "Ladle",
    "Human mouth",
    "Dairy",
    "Dice",
    "Oven",
    "Dinosaur",
    "Ratchet",
    "Couch",
    "Cricket ball",
    "Winter melon",
    "Spatula",
    "Whiteboard",
    "Pencil sharpener",
    "Door",
    "Hat",
    "Shower",
    "Eraser",
    "Fedora",
    "Guacamole",
    "Dagger",
    "Scarf",
    "Dolphin",
    "Sombrero",
    "Tin can",
    "Mug",
    "Tap",
    "Harbor seal",
    "Stretcher",
    "Can opener",
    "Goggles",
    "Human body",
    "Roller skates",
    "Coffee cup",
    "Cutting board",
    "Blender",
    "Plumbing fixture",
    "Stop sign",
    "Office supplies",
    "Volleyball",
    "Vase",
    "Slow cooker",
    "Wardrobe",
    "Coffee",
    "Whisk",
    "Paper towel",
    "Personal care",
    "Food",
    "Sun hat",
    "Tree house",
    "Flying disc",
    "Skirt",
    "Gas stove",
    "Salt and pepper shakers",
    "Mechanical fan",
    "Face powder",
    "Fax",
    "Fruit",
    "French fries",
    "Nightstand",
    "Barrel",
    "Kite",
    "Tart",
    "Treadmill",
    "Fox",
    "Flag",
    "Horn",
    "Window blind",
    "Human foot",
    "Golf cart",
    "Jacket",
    "Egg",
    "Street light",
    "Guitar",
    "Pillow",
    "Human leg",
    "Isopod",
    "Grape",
    "Human ear",
    "Power plugs and sockets",
    "Panda",
    "Giraffe",
    "Woman",
    "Door handle",
    "Rhinoceros",
    "Bathtub",
    "Goldfish",
    "Houseplant",
    "Goat",
    "Baseball bat",
    "Baseball glove",
    "Mixing bowl",
    "Marine invertebrates",
    "Kitchen utensil",
    "Light switch",
    "House",
    "Horse",
    "Stationary bicycle",
    "Hammer",
    "Ceiling fan",
    "Sofa bed",
    "Adhesive tape",
    "Harp",
    "Sandal",
    "Bicycle helmet",
    "Saucer",
    "Harpsichord",
    "Human hair",
    "Heater",
    "Harmonica",
    "Hamster",
    "Curtain",
    "Bed",
    "Kettle",
    "Fireplace",
    "Scale",
    "Drinking straw",
    "Insect",
    "Hair dryer",
    "Kitchenware",
    "Indoor rower",
    "Invertebrate",
    "Food processor",
    "Bookcase",
    "Refrigerator",
    "Wood-burning stove",
    "Punching bag",
    "Common fig",
    "Cocktail shaker",
    "Jaguar",
    "Golf ball",
    "Fashion accessory",
    "Alarm clock",
    "Filing cabinet",
    "Artichoke",
    "Table",
    "Tableware",
    "Kangaroo",
    "Koala",
    "Knife",
    "Bottle",
    "Bottle opener",
    "Lynx",
    "Lavender",
    "Lighthouse",
    "Dumbbell",
    "Human head",
    "Bowl",
    "Humidifier",
    "Porch",
    "Lizard",
    "Billiard table",
    "Mammal",
    "Mouse",
    "Motorcycle",
    "Musical instrument",
    "Swim cap",
    "Frying pan",
    "Snowplow",
    "Bathroom cabinet",
    "Missile",
    "Bust",
    "Man",
    "Waffle iron",
    "Milk",
    "Ring binder",
    "Plate",
    "Mobile phone",
    "Baked goods",
    "Mushroom",
    "Crutch",
    "Pitcher",
    "Mirror",
    "Lifejacket",
    "Table tennis racket",
    "Pencil case",
    "Musical keyboard",
    "Scoreboard",
    "Briefcase",
    "Kitchen knife",
    "Nail",
    "Tennis ball",
    "Plastic bag",
    "Oboe",
    "Chest of drawers",
    "Ostrich",
    "Piano",
    "Girl",
    "Plant",
    "Potato",
    "Hair spray",
    "Sports equipment",
    "Pasta",
    "Penguin",
    "Pumpkin",
    "Pear",
    "Infant bed",
    "Polar bear",
    "Mixer",
    "Cupboard",
    "Jacuzzi",
    "Pizza",
    "Digital clock",
    "Pig",
    "Reptile",
    "Rifle",
    "Lipstick",
    "Skateboard",
    "Raven",
    "High heels",
    "Red panda",
    "Rose",
    "Rabbit",
    "Sculpture",
    "Saxophone",
    "Shotgun",
    "Seafood",
    "Submarine sandwich",
    "Snowboard",
    "Sword",
    "Picture frame",
    "Sushi",
    "Loveseat",
    "Ski",
    "Squirrel",
    "Tripod",
    "Stethoscope",
    "Submarine",
    "Scorpion",
    "Segway",
    "Training bench",
    "Snake",
    "Coffee table",
    "Skyscraper",
    "Sheep",
    "Television",
    "Trombone",
    "Tea",
    "Tank",
    "Taco",
    "Telephone",
    "Torch",
    "Tiger",
    "Strawberry",
    "Trumpet",
    "Tree",
    "Tomato",
    "Train",
    "Tool",
    "Picnic basket",
    "Cooking spray",
    "Trousers",
    "Bowling equipment",
    "Football helmet",
    "Truck",
    "Measuring cup",
    "Coffeemaker",
    "Violin",
    "Vehicle",
    "Handbag",
    "Paper cutter",
    "Wine",
    "Weapon",
    "Wheel",
    "Worm",
    "Wok",
    "Whale",
    "Zebra",
    "Auto part",
    "Jug",
    "Pizza cutter",
    "Cream",
    "Monkey",
    "Lion",
    "Bread",
    "Platter",
    "Chicken",
    "Eagle",
    "Helicopter",
    "Owl",
    "Duck",
    "Turtle",
    "Hippopotamus",
    "Crocodile",
    "Toilet",
    "Toilet paper",
    "Squid",
    "Clothing",
    "Footwear",
    "Lemon",
    "Spider",
    "Deer",
    "Frog",
    "Banana",
    "Rocket",
    "Wine glass",
    "Countertop",
    "Tablet computer",
    "Waste container",
    "Swimming pool",
    "Dog",
    "Book",
    "Elephant",
    "Shark",
    "Candle",
    "Leopard",
    "Axe",
    "Hand dryer",
    "Soap dispenser",
    "Porcupine",
    "Flower",
    "Canary",
    "Cheetah",
    "Palm tree",
    "Hamburger",
    "Maple",
    "Building",
    "Fish",
    "Lobster",
    "Asparagus",
    "Furniture",
    "Hedgehog",
    "Airplane",
    "Spoon",
    "Otter",
    "Bull",
    "Oyster",
    "Horizontal bar",
    "Convenience store",
    "Bomb",
    "Bench",
    "Ice cream",
    "Caterpillar",
    "Butterfly",
    "Parachute",
    "Orange",
    "Antelope",
    "Beaker",
    "Moths and butterflies",
    "Window",
    "Closet",
    "Castle",
    "Jellyfish",
    "Goose",
    "Mule",
    "Swan",
    "Peach",
    "Coconut",
    "Seat belt",
    "Raccoon",
    "Chisel",
    "Fork",
    "Lamp",
    "Camera",
    "Squash",
    "Racket",
    "Human face",
    "Human arm",
    "Vegetable",
    "Diaper",
    "Unicycle",
    "Falcon",
    "Chime",
    "Snail",
    "Shellfish",
    "Cabbage",
    "Carrot",
    "Mango",
    "Jeans",
    "Flowerpot",
    "Pineapple",
    "Drawer",
    "Stool",
    "Envelope",
    "Cake",
    "Dragonfly",
    "Sunflower",
    "Microwave oven",
    "Honeycomb",
    "Marine mammal",
    "Sea lion",
    "Ladybug",
    "Shelf",
    "Watch",
    "Candy",
    "Salad",
    "Parrot",
    "Handgun",
    "Sparrow",
    "Van",
    "Grinder",
    "Spice rack",
    "Light bulb",
    "Corded phone",
    "Sports uniform",
    "Tennis racket",
    "Wall clock",
    "Serving tray",
    "Kitchen & dining room table",
    "Dog bed",
    "Cake stand",
    "Cat furniture",
    "Bathroom accessory",
    "Facial tissue holder",
    "Pressure cooker",
    "Kitchen appliance",
    "Tire",
    "Ruler",
    "Luggage and bags",
    "Microphone",
    "Broccoli",
    "Umbrella",
    "Pastry",
    "Grapefruit",
    "Band-aid",
    "Animal",
    "Bell pepper",
    "Turkey",
    "Lily",
    "Pomegranate",
    "Doughnut",
    "Glasses",
    "Human nose",
    "Pen",
    "Ant",
    "Car",
    "Aircraft",
    "Human hand",
    "Skunk",
    "Teddy bear",
    "Watermelon",
    "Cantaloupe",
    "Dishwasher",
    "Flute",
    "Balance beam",
    "Sandwich",
    "Shrimp",
    "Sewing machine",
    "Binoculars",
    "Rays and skates",
    "Ipod",
    "Accordion",
    "Willow",
    "Crab",
    "Crown",
    "Seahorse",
    "Perfume",
    "Alpaca",
    "Taxi",
    "Canoe",
    "Remote control",
    "Wheelchair",
    "Rugby ball",
    "Armadillo",
    "Maracas",
    "Helmet",
]

# --- Elasticsearch settings ---
ELASTIC_HOST = _env("ELASTIC_HOST", "localhost")
ELASTIC_PORT = _env("ELASTIC_PORT", "9200")
ELASTIC_SCHEME = _env("ELASTIC_SCHEME", "http")
TRANSCRIPT_INDEX = _env("TRANSCRIPT_INDEX", "video_text_segments")
# Backwards-compatible alias: this index now stores transcript, OCR, and captions.
MULTIMODAL_TEXT_INDEX = TRANSCRIPT_INDEX
DEFAULT_FALLBACK_FPS = _env_float("DEFAULT_FALLBACK_FPS", 25.0)

# --- Evaluation Server Settings ---
# ⚠️ KHI SERVER THAY ĐỔI → CHỈ SỬA 3 DÒNG DƯỚI ĐÂY
EVAL_SERVER_URL = _env("EVAL_SERVER_URL", "http://192.168.20.156:5601")
SESSION_ID = _env("SESSION_ID", "LIj1h0LIHorVZYS7hXUe9bMbDxGJBmg-")
EVALUATION_ID = _env("EVALUATION_ID", "44457530-7aaa-4186-a4df-bcbaf9908d33")

# Credentials (không dùng nếu có SESSION_ID sẵn)
EVAL_USERNAME = _env("EVAL_USERNAME", "team006")
EVAL_PASSWORD = _env("EVAL_PASSWORD", "123456")
